apiVersion: v1
data:
  MONGODB_HOST: mongodb-service
kind: ConfigMap
metadata:
  name: mongodb-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ivot-backend-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ivot-backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivot-backend
  name: ivot-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivot-backend
  template:
    metadata:
      labels:
        app: ivot-backend
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: MONGODB_USERNAME
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGODB_PASSWORD
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: MONGODB_HOST
              name: mongodb-configmap
        image: jitn/ivotback:v2
        name: ivot-backend
        ports:
        - containerPort: 8081
