apiVersion: v1
data:
  MONGODB_DATABASE: devops-ivot
  MONGODB_HOST: devops-tools.3zejp.mongodb.net
  NODE_APP_API_REPORTING: https://api.victorops.com/api-reporting/v1/team/team-xwG7ASzGf9kflhfy/oncall/log?start=
  NODE_PORT: "8081"
kind: ConfigMap
metadata:
  name: mongodb-configmap
---
apiVersion: v1
data:
  MONGODB_PASSWORD: MkJGZ0xCWnVXdHFPaW1aYg==
  MONGODB_USERNAME: ZGV2b3BzLXBheW1lbnRz
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
---
apiVersion: v1
data:
  NODE_APP_X_VO_API_ID: ZGU1ZTgyY2I=
  NODE_APP_X_VO_API_KEY: NTVkODY3MGUxZjI1N2YyN2ZiYzNlZTg4YTIzZjI5MjM=
kind: Secret
metadata:
  name: victorops-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: ivot-backend
spec:
  ports:
  - nodePort: 30036
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ivot-backend
    role: ivot-backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivot-backend
    role: ivot-backend
  name: ivot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivot-backend
  template:
    metadata:
      labels:
        app: ivot-backend
    spec:
      containers:
      - env:
        - name: NODE_APP_X_VO_API_ID
          valueFrom:
            secretKeyRef:
              key: NODE_APP_X_VO_API_ID
              name: victorops-secret
        - name: NODE_APP_X_VO_API_KEY
          valueFrom:
            secretKeyRef:
              key: NODE_APP_X_VO_API_KEY
              name: victorops-secret
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: MONGODB_USERNAME
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGODB_PASSWORD
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: MONGODB_HOST
              name: mongodb-configmap
        - name: ME_CONFIG_MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MONGODB_DATABASE
              name: mongodb-configmap
        - name: ME_CONFIG_NODE_PORT
          valueFrom:
            configMapKeyRef:
              key: NODE_PORT
              name: mongodb-configmap
        - name: NODE_APP_API_REPORTING
          valueFrom:
            configMapKeyRef:
              key: NODE_APP_API_REPORTING
              name: mongodb-configmap
        image: jitn/ivotback:v7
        name: ivot-backend
        ports:
        - containerPort: 8080
